buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // Стабільна версія плагіна, яка ще нормально перетравлює API 19
        classpath 'com.android.tools.build:gradle:7.4.2'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}
