plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ontario.app'
    compileSdk 33 // Використовуємо сучасний SDK для компіляції

    defaultConfig {
        applicationId "com.ontario.app"
        minSdk 19    // Android 4.4.4 KitKat
        targetSdk 19
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    // Жодних зовнішніх бібліотек для мінімалізму
}
